/**
 * Official Intel / AMD desktop CPU specs for CMS + PDP.
 * Clocks, cores, TDP, cache, and memory from Intel ARK and AMD product pages.
 */

export type ProcessorOfficialSpec = Record<string, string>;

const INTEL_UHD_RES =
  'Max Resolution (HDMI): 4096 x 2160 @ 60Hz\nMax Resolution (DP): 7680 x 4320 @ 60Hz\nMax Resolution (eDP - Integrated Flat Panel): 5120 x 3200 @ 120Hz';

const AMD_RADEON_RES =
  'Max Resolution (HDMI): 4096 x 2160 @ 60Hz\nMax Resolution (DisplayPort): 3840 x 2160 @ 60Hz';

const NONE = 'None (Discrete GPU Required)';

function intel(spec: ProcessorOfficialSpec): ProcessorOfficialSpec {
  return {
    memory_channels: '2',
    pcie_version: spec.pcie_version || 'PCIe 5.0',
    ...spec,
  };
}

function amd(spec: ProcessorOfficialSpec): ProcessorOfficialSpec {
  return {
    memory_channels: '2',
    ...spec,
  };
}

/** Keyed by product slug */
export const PROCESSOR_OFFICIAL_SPECS: Record<string, ProcessorOfficialSpec> = {
  'amd-athlon-pro-300ge-processor': amd({
    processor_model: 'AMD Athlon',
    model_number: 'Athlon PRO 300GE',
    generation: 'Athlon 3000 Series',
    number_of_cores: '2 Core',
    number_of_threads: '4 Threads',
    base_clock: '3.4',
    boost_clock: '3.4',
    cache_size: '4 MB',
    l2_cache: '1 MB',
    socket_type: 'AM4',
    tdp: '35W',
    integrated_graphics: 'AMD Radeon Vega 3',
    gpu_frequency: '1100 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-2666',
    max_memory_size: '64 GB',
    max_memory_bandwidth: '42.7 GB/s',
    pcie_version: 'PCIe 3.0',
  }),
  'amd-ryzen-3-3200g': amd({
    processor_model: 'Ryzen 3',
    model_number: 'Ryzen 3 3200G',
    generation: 'Ryzen 3000 Series',
    number_of_cores: '4 Core',
    number_of_threads: '4 Threads',
    base_clock: '3.6',
    boost_clock: '4.0',
    cache_size: '4 MB',
    l2_cache: '2 MB',
    socket_type: 'AM4',
    tdp: '65W',
    integrated_graphics: 'AMD Radeon RX Vega 8',
    gpu_frequency: '1250 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-2933',
    max_memory_size: '64 GB',
    max_memory_bandwidth: '46.9 GB/s',
    pcie_version: 'PCIe 3.0',
  }),
  'amd-ryzen-3-4100-processor': amd({
    processor_model: 'Ryzen 3',
    model_number: 'Ryzen 3 4100',
    generation: 'Ryzen 4000 Series',
    number_of_cores: '4 Core',
    number_of_threads: '8 Threads',
    base_clock: '3.8',
    boost_clock: '4.0',
    cache_size: '4 MB',
    l2_cache: '2 MB',
    socket_type: 'AM4',
    tdp: '65W',
    integrated_graphics: NONE,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-3200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '51.2 GB/s',
    pcie_version: 'PCIe 3.0',
  }),
  'amd-ryzen-5-2400g-processor': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 2400G',
    generation: 'Ryzen 2000 Series',
    number_of_cores: '4 Core',
    number_of_threads: '8 Threads',
    base_clock: '3.6',
    boost_clock: '3.9',
    cache_size: '4 MB',
    l2_cache: '2 MB',
    socket_type: 'AM4',
    tdp: '65W',
    integrated_graphics: 'AMD Radeon RX Vega 11',
    gpu_frequency: '1250 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-2933',
    max_memory_size: '64 GB',
    max_memory_bandwidth: '46.9 GB/s',
    pcie_version: 'PCIe 3.0',
  }),
  'amd-ryzen-5-3400g-processor': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 3400G',
    generation: 'Ryzen 3000 Series',
    number_of_cores: '4 Core',
    number_of_threads: '8 Threads',
    base_clock: '3.7',
    boost_clock: '4.2',
    cache_size: '4 MB',
    l2_cache: '2 MB',
    socket_type: 'AM4',
    tdp: '65W',
    integrated_graphics: 'AMD Radeon RX Vega 11',
    gpu_frequency: '1400 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-2933',
    max_memory_size: '64 GB',
    max_memory_bandwidth: '46.9 GB/s',
    pcie_version: 'PCIe 3.0',
  }),
  'amd-ryzen-5-5500-processor': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 5500',
    generation: 'Ryzen 5000 Series',
    number_of_cores: '6 Core',
    number_of_threads: '12 Threads',
    base_clock: '3.6',
    boost_clock: '4.2',
    cache_size: '16 MB',
    l2_cache: '3 MB',
    socket_type: 'AM4',
    tdp: '65W',
    integrated_graphics: NONE,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-3200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '51.2 GB/s',
    pcie_version: 'PCIe 3.0',
  }),
  'amd-ryzen-5-5500gt-processor': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 5500GT',
    generation: 'Ryzen 5000 Series',
    number_of_cores: '6 Core',
    number_of_threads: '12 Threads',
    base_clock: '3.6',
    boost_clock: '4.4',
    cache_size: '16 MB',
    l2_cache: '3 MB',
    socket_type: 'AM4',
    tdp: '65W',
    integrated_graphics: 'AMD Radeon RX Vega 7',
    gpu_frequency: '1900 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-3200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '51.2 GB/s',
    pcie_version: 'PCIe 3.0',
  }),
  'amd-ryzen-5-5600': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 5600',
    generation: 'Ryzen 5000 Series',
    number_of_cores: '6 Core',
    number_of_threads: '12 Threads',
    base_clock: '3.5',
    boost_clock: '4.4',
    cache_size: '32 MB',
    l2_cache: '3 MB',
    socket_type: 'AM4',
    tdp: '65W',
    integrated_graphics: NONE,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-3200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '51.2 GB/s',
    pcie_version: 'PCIe 4.0',
  }),
  'amd-ryzen-5-5600gt-processor': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 5600GT',
    generation: 'Ryzen 5000 Series',
    number_of_cores: '6 Core',
    number_of_threads: '12 Threads',
    base_clock: '3.6',
    boost_clock: '4.6',
    cache_size: '16 MB',
    l2_cache: '3 MB',
    socket_type: 'AM4',
    tdp: '65W',
    integrated_graphics: 'AMD Radeon RX Vega 7',
    gpu_frequency: '1900 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-3200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '51.2 GB/s',
    pcie_version: 'PCIe 3.0',
  }),
  'amd-ryzen-5-5600x': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 5600X',
    generation: 'Ryzen 5000 Series',
    number_of_cores: '6 Core',
    number_of_threads: '12 Threads',
    base_clock: '3.7',
    boost_clock: '4.6',
    cache_size: '32 MB',
    l2_cache: '3 MB',
    socket_type: 'AM4',
    tdp: '65W',
    integrated_graphics: NONE,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-3200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '51.2 GB/s',
    pcie_version: 'PCIe 4.0',
  }),
  'amd-ryzen-5-7500f-processor': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 7500F',
    generation: 'Ryzen 7000 Series',
    number_of_cores: '6 Core',
    number_of_threads: '12 Threads',
    base_clock: '3.7',
    boost_clock: '5.0',
    cache_size: '32 MB',
    l2_cache: '6 MB',
    socket_type: 'AM5',
    tdp: '65W',
    integrated_graphics: NONE,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '83.2 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-5-7600': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 7600',
    generation: 'Ryzen 7000 Series',
    number_of_cores: '6 Core',
    number_of_threads: '12 Threads',
    base_clock: '3.8',
    boost_clock: '5.1',
    cache_size: '32 MB',
    l2_cache: '6 MB',
    socket_type: 'AM5',
    tdp: '65W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '83.2 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-5-7600x-processor': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 7600X',
    generation: 'Ryzen 7000 Series',
    number_of_cores: '6 Core',
    number_of_threads: '12 Threads',
    base_clock: '4.7',
    boost_clock: '5.3',
    cache_size: '32 MB',
    l2_cache: '6 MB',
    socket_type: 'AM5',
    tdp: '105W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '83.2 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-5-8400f-processor': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 8400F',
    generation: 'Ryzen 8000 Series',
    number_of_cores: '6 Core',
    number_of_threads: '12 Threads',
    base_clock: '4.2',
    boost_clock: '4.7',
    cache_size: '16 MB',
    l2_cache: '6 MB',
    socket_type: 'AM5',
    tdp: '65W',
    integrated_graphics: NONE,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5200',
    max_memory_size: '256 GB',
    max_memory_bandwidth: '83.2 GB/s',
    pcie_version: 'PCIe 4.0',
  }),
  'amd-ryzen-5-8500g-processor': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 8500G',
    generation: 'Ryzen 8000 Series',
    number_of_cores: '6 Core',
    number_of_threads: '12 Threads',
    base_clock: '3.5',
    boost_clock: '5.0',
    cache_size: '16 MB',
    l2_cache: '6 MB',
    socket_type: 'AM5',
    tdp: '65W',
    integrated_graphics: 'AMD Radeon 740M',
    gpu_frequency: '2800 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5200',
    max_memory_size: '256 GB',
    max_memory_bandwidth: '83.2 GB/s',
    pcie_version: 'PCIe 4.0',
  }),
  'amd-ryzen-5-8600g-processor': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 8600G',
    generation: 'Ryzen 8000 Series',
    number_of_cores: '6 Core',
    number_of_threads: '12 Threads',
    base_clock: '4.3',
    boost_clock: '5.0',
    cache_size: '16 MB',
    l2_cache: '6 MB',
    socket_type: 'AM5',
    tdp: '65W',
    integrated_graphics: 'AMD Radeon 760M',
    gpu_frequency: '2800 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5200',
    max_memory_size: '256 GB',
    max_memory_bandwidth: '83.2 GB/s',
    pcie_version: 'PCIe 4.0',
  }),
  'amd-ryzen-5-9600x-gaming-processor': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 9600X',
    generation: 'Ryzen 9000 Series',
    number_of_cores: '6 Core',
    number_of_threads: '12 Threads',
    base_clock: '3.9',
    boost_clock: '5.4',
    cache_size: '32 MB',
    l2_cache: '6 MB',
    socket_type: 'AM5',
    tdp: '65W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5600',
    max_memory_size: '192 GB',
    max_memory_bandwidth: '89.6 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-5-pro-2400ge-processor': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 PRO 2400GE',
    generation: 'Ryzen 2000 Series',
    number_of_cores: '4 Core',
    number_of_threads: '8 Threads',
    base_clock: '3.2',
    boost_clock: '3.8',
    cache_size: '4 MB',
    l2_cache: '2 MB',
    socket_type: 'AM4',
    tdp: '35W',
    integrated_graphics: 'AMD Radeon RX Vega 11',
    gpu_frequency: '1250 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-2933',
    max_memory_size: '64 GB',
    max_memory_bandwidth: '46.9 GB/s',
    pcie_version: 'PCIe 3.0',
  }),
  'amd-ryzen-5-pro-5650g-processor': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 PRO 5650G',
    generation: 'Ryzen 5000 Series',
    number_of_cores: '6 Core',
    number_of_threads: '12 Threads',
    base_clock: '3.9',
    boost_clock: '4.4',
    cache_size: '16 MB',
    l2_cache: '3 MB',
    socket_type: 'AM4',
    tdp: '65W',
    integrated_graphics: 'AMD Radeon RX Vega 7',
    gpu_frequency: '1900 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-3200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '51.2 GB/s',
    pcie_version: 'PCIe 3.0',
  }),
  'amd-ryzen-5-pro-5650ge-processor': amd({
    processor_model: 'Ryzen 5',
    model_number: 'Ryzen 5 PRO 5650GE',
    generation: 'Ryzen 5000 Series',
    number_of_cores: '6 Core',
    number_of_threads: '12 Threads',
    base_clock: '3.4',
    boost_clock: '4.4',
    cache_size: '16 MB',
    l2_cache: '3 MB',
    socket_type: 'AM4',
    tdp: '35W',
    integrated_graphics: 'AMD Radeon RX Vega 7',
    gpu_frequency: '1900 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-3200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '51.2 GB/s',
    pcie_version: 'PCIe 3.0',
  }),
  'amd-ryzen-7-5700g-processor': amd({
    processor_model: 'Ryzen 7',
    model_number: 'Ryzen 7 5700G',
    generation: 'Ryzen 5000 Series',
    number_of_cores: '8 Core',
    number_of_threads: '16 Threads',
    base_clock: '3.8',
    boost_clock: '4.6',
    cache_size: '16 MB',
    l2_cache: '4 MB',
    socket_type: 'AM4',
    tdp: '65W',
    integrated_graphics: 'AMD Radeon RX Vega 8',
    gpu_frequency: '2000 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-3200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '51.2 GB/s',
    pcie_version: 'PCIe 3.0',
  }),
  'amd-ryzen-7-5700x-processor': amd({
    processor_model: 'Ryzen 7',
    model_number: 'Ryzen 7 5700X',
    generation: 'Ryzen 5000 Series',
    number_of_cores: '8 Core',
    number_of_threads: '16 Threads',
    base_clock: '3.4',
    boost_clock: '4.6',
    cache_size: '32 MB',
    l2_cache: '4 MB',
    socket_type: 'AM4',
    tdp: '65W',
    integrated_graphics: NONE,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-3200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '51.2 GB/s',
    pcie_version: 'PCIe 4.0',
  }),
  'amd-ryzen-7-7700-processor': amd({
    processor_model: 'Ryzen 7',
    model_number: 'Ryzen 7 7700',
    generation: 'Ryzen 7000 Series',
    number_of_cores: '8 Core',
    number_of_threads: '16 Threads',
    base_clock: '3.8',
    boost_clock: '5.3',
    cache_size: '32 MB',
    l2_cache: '8 MB',
    socket_type: 'AM5',
    tdp: '65W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '83.2 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-7-7700x-processor': amd({
    processor_model: 'Ryzen 7',
    model_number: 'Ryzen 7 7700X',
    generation: 'Ryzen 7000 Series',
    number_of_cores: '8 Core',
    number_of_threads: '16 Threads',
    base_clock: '4.5',
    boost_clock: '5.4',
    cache_size: '32 MB',
    l2_cache: '8 MB',
    socket_type: 'AM5',
    tdp: '105W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '83.2 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-7-7800x3d': amd({
    processor_model: 'Ryzen 7',
    model_number: 'Ryzen 7 7800X3D',
    generation: 'Ryzen 7000 Series',
    number_of_cores: '8 Core',
    number_of_threads: '16 Threads',
    base_clock: '4.2',
    boost_clock: '5.0',
    cache_size: '96 MB',
    l2_cache: '8 MB',
    socket_type: 'AM5',
    tdp: '120W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '83.2 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-7-8700g-processor': amd({
    processor_model: 'Ryzen 7',
    model_number: 'Ryzen 7 8700G',
    generation: 'Ryzen 8000 Series',
    number_of_cores: '8 Core',
    number_of_threads: '16 Threads',
    base_clock: '4.2',
    boost_clock: '5.1',
    cache_size: '16 MB',
    l2_cache: '8 MB',
    socket_type: 'AM5',
    tdp: '65W',
    integrated_graphics: 'AMD Radeon 780M',
    gpu_frequency: '2900 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5200',
    max_memory_size: '256 GB',
    max_memory_bandwidth: '83.2 GB/s',
    pcie_version: 'PCIe 4.0',
  }),
  'amd-ryzen-7-9700x-gaming-processor': amd({
    processor_model: 'Ryzen 7',
    model_number: 'Ryzen 7 9700X',
    generation: 'Ryzen 9000 Series',
    number_of_cores: '8 Core',
    number_of_threads: '16 Threads',
    base_clock: '3.8',
    boost_clock: '5.5',
    cache_size: '32 MB',
    l2_cache: '8 MB',
    socket_type: 'AM5',
    tdp: '65W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5600',
    max_memory_size: '192 GB',
    max_memory_bandwidth: '89.6 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-7-9800x3d-processor': amd({
    processor_model: 'Ryzen 7',
    model_number: 'Ryzen 7 9800X3D',
    generation: 'Ryzen 9000 Series',
    number_of_cores: '8 Core',
    number_of_threads: '16 Threads',
    base_clock: '4.7',
    boost_clock: '5.2',
    cache_size: '96 MB',
    l2_cache: '8 MB',
    socket_type: 'AM5',
    tdp: '120W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5600',
    max_memory_size: '192 GB',
    max_memory_bandwidth: '89.6 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-7-9850x3d-processor': amd({
    processor_model: 'Ryzen 7',
    model_number: 'Ryzen 7 9850X3D',
    generation: 'Ryzen 9000 Series',
    number_of_cores: '8 Core',
    number_of_threads: '16 Threads',
    base_clock: '4.7',
    boost_clock: '5.6',
    cache_size: '96 MB',
    l2_cache: '8 MB',
    socket_type: 'AM5',
    tdp: '120W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5600',
    max_memory_size: '192 GB',
    max_memory_bandwidth: '89.6 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-7-pro-5755g-processor': amd({
    processor_model: 'Ryzen 7',
    model_number: 'Ryzen 7 PRO 5755G',
    generation: 'Ryzen 5000 Series',
    number_of_cores: '8 Core',
    number_of_threads: '16 Threads',
    base_clock: '3.8',
    boost_clock: '4.6',
    cache_size: '16 MB',
    l2_cache: '4 MB',
    socket_type: 'AM4',
    tdp: '65W',
    integrated_graphics: 'AMD Radeon RX Vega 8',
    gpu_frequency: '2000 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-3200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '51.2 GB/s',
    pcie_version: 'PCIe 3.0',
  }),
  'amd-ryzen-9-5900x-processor': amd({
    processor_model: 'Ryzen 9',
    model_number: 'Ryzen 9 5900X',
    generation: 'Ryzen 5000 Series',
    number_of_cores: '12 Core',
    number_of_threads: '24 Threads',
    base_clock: '3.7',
    boost_clock: '4.8',
    cache_size: '64 MB',
    l2_cache: '6 MB',
    socket_type: 'AM4',
    tdp: '105W',
    integrated_graphics: NONE,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-3200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '51.2 GB/s',
    pcie_version: 'PCIe 4.0',
  }),
  'amd-ryzen-9-5950x-processor': amd({
    processor_model: 'Ryzen 9',
    model_number: 'Ryzen 9 5950X',
    generation: 'Ryzen 5000 Series',
    number_of_cores: '16 Core',
    number_of_threads: '32 Threads',
    base_clock: '3.4',
    boost_clock: '4.9',
    cache_size: '64 MB',
    l2_cache: '8 MB',
    socket_type: 'AM4',
    tdp: '105W',
    integrated_graphics: NONE,
    memory_type: 'DDR4',
    max_memory_speed: 'DDR4-3200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '51.2 GB/s',
    pcie_version: 'PCIe 4.0',
  }),
  'amd-ryzen-9-7900x-processor': amd({
    processor_model: 'Ryzen 9',
    model_number: 'Ryzen 9 7900X',
    generation: 'Ryzen 7000 Series',
    number_of_cores: '12 Core',
    number_of_threads: '24 Threads',
    base_clock: '4.7',
    boost_clock: '5.6',
    cache_size: '64 MB',
    l2_cache: '12 MB',
    socket_type: 'AM5',
    tdp: '170W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '83.2 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-9-7950x': amd({
    processor_model: 'Ryzen 9',
    model_number: 'Ryzen 9 7950X',
    generation: 'Ryzen 7000 Series',
    number_of_cores: '16 Core',
    number_of_threads: '32 Threads',
    base_clock: '4.5',
    boost_clock: '5.7',
    cache_size: '64 MB',
    l2_cache: '16 MB',
    socket_type: 'AM5',
    tdp: '170W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '83.2 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-9-7950x3d-processor': amd({
    processor_model: 'Ryzen 9',
    model_number: 'Ryzen 9 7950X3D',
    generation: 'Ryzen 7000 Series',
    number_of_cores: '16 Core',
    number_of_threads: '32 Threads',
    base_clock: '4.2',
    boost_clock: '5.7',
    cache_size: '128 MB',
    l2_cache: '16 MB',
    socket_type: 'AM5',
    tdp: '120W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5200',
    max_memory_size: '128 GB',
    max_memory_bandwidth: '83.2 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-9-9900x-gaming-processor': amd({
    processor_model: 'Ryzen 9',
    model_number: 'Ryzen 9 9900X',
    generation: 'Ryzen 9000 Series',
    number_of_cores: '12 Core',
    number_of_threads: '24 Threads',
    base_clock: '4.4',
    boost_clock: '5.6',
    cache_size: '64 MB',
    l2_cache: '12 MB',
    socket_type: 'AM5',
    tdp: '120W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5600',
    max_memory_size: '192 GB',
    max_memory_bandwidth: '89.6 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-9-9900x3d-processor': amd({
    processor_model: 'Ryzen 9',
    model_number: 'Ryzen 9 9900X3D',
    generation: 'Ryzen 9000 Series',
    number_of_cores: '12 Core',
    number_of_threads: '24 Threads',
    base_clock: '4.4',
    boost_clock: '5.5',
    cache_size: '128 MB',
    l2_cache: '12 MB',
    socket_type: 'AM5',
    tdp: '120W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5600',
    max_memory_size: '192 GB',
    max_memory_bandwidth: '89.6 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-9-9950x-gaming-processor': amd({
    processor_model: 'Ryzen 9',
    model_number: 'Ryzen 9 9950X',
    generation: 'Ryzen 9000 Series',
    number_of_cores: '16 Core',
    number_of_threads: '32 Threads',
    base_clock: '4.3',
    boost_clock: '5.7',
    cache_size: '64 MB',
    l2_cache: '16 MB',
    socket_type: 'AM5',
    tdp: '170W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5600',
    max_memory_size: '192 GB',
    max_memory_bandwidth: '89.6 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
  'amd-ryzen-9-9950x3d-processor': amd({
    processor_model: 'Ryzen 9',
    model_number: 'Ryzen 9 9950X3D',
    generation: 'Ryzen 9000 Series',
    number_of_cores: '16 Core',
    number_of_threads: '32 Threads',
    base_clock: '4.3',
    boost_clock: '5.7',
    cache_size: '128 MB',
    l2_cache: '16 MB',
    socket_type: 'AM5',
    tdp: '170W',
    integrated_graphics: 'AMD Radeon Graphics',
    gpu_frequency: '2200 MHz',
    max_resolution: AMD_RADEON_RES,
    memory_type: 'DDR5',
    max_memory_speed: 'DDR5-5600',
    max_memory_size: '192 GB',
    max_memory_bandwidth: '89.6 GB/s',
    pcie_version: 'PCIe 5.0',
  }),
};

function addIntelBatch() {
  const ten = '10th Gen (Comet Lake)';
  const eleven = '11th Gen (Rocket Lake)';
  const twelve = '12th Gen (Alder Lake)';
  const thirteen = '13th Gen (Raptor Lake)';
  const fourteen = '14th Gen (Raptor Lake Refresh)';
  const ultra2 = 'Ultra Series 2';

  const rows: Record<string, ProcessorOfficialSpec> = {
    'intel-pentium-gold-g6400-processor': intel({
      processor_model: 'Intel Pentium',
      model_number: 'Pentium Gold G6400',
      generation: ten,
      number_of_cores: '2 Core',
      number_of_threads: '4 Threads',
      base_clock: '4.0',
      boost_clock: '4.0',
      cache_size: '4 MB',
      l2_cache: '0.5 MB',
      socket_type: 'LGA 1200',
      tdp: '58W',
      integrated_graphics: 'Intel UHD Graphics 610',
      gpu_frequency: '1.05 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4',
      max_memory_speed: 'DDR4-2666',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '41.6 GB/s',
      pcie_version: 'PCIe 3.0',
    }),
    'intel-core-i3-10100-processor': intel({
      processor_model: 'Intel Core i3',
      model_number: 'Core i3-10100',
      generation: ten,
      number_of_cores: '4 Core',
      number_of_threads: '8 Threads',
      base_clock: '3.6',
      boost_clock: '4.3',
      cache_size: '6 MB',
      l2_cache: '1 MB',
      socket_type: 'LGA 1200',
      tdp: '65W',
      max_turbo_power: '90W',
      integrated_graphics: 'Intel UHD Graphics 630',
      gpu_frequency: '1.10 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4',
      max_memory_speed: 'DDR4-2666',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '41.6 GB/s',
      pcie_version: 'PCIe 3.0',
    }),
    'intel-core-i3-10105-10th-gen-processor': intel({
      processor_model: 'Intel Core i3',
      model_number: 'Core i3-10105',
      generation: ten,
      number_of_cores: '4 Core',
      number_of_threads: '8 Threads',
      base_clock: '3.7',
      boost_clock: '4.4',
      cache_size: '6 MB',
      l2_cache: '1 MB',
      socket_type: 'LGA 1200',
      tdp: '65W',
      integrated_graphics: 'Intel UHD Graphics 630',
      gpu_frequency: '1.10 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4',
      max_memory_speed: 'DDR4-2666',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '41.6 GB/s',
      pcie_version: 'PCIe 3.0',
    }),
    'intel-core-i5-10400-processor': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-10400',
      generation: ten,
      number_of_cores: '6 Core',
      number_of_threads: '12 Threads',
      base_clock: '2.9',
      boost_clock: '4.3',
      cache_size: '12 MB',
      l2_cache: '1.5 MB',
      socket_type: 'LGA 1200',
      tdp: '65W',
      integrated_graphics: 'Intel UHD Graphics 630',
      gpu_frequency: '1.20 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4',
      max_memory_speed: 'DDR4-2666',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '41.6 GB/s',
      pcie_version: 'PCIe 3.0',
    }),
    'intel-core-i5-10500-processor': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-10500',
      generation: ten,
      number_of_cores: '6 Core',
      number_of_threads: '12 Threads',
      base_clock: '3.1',
      boost_clock: '4.5',
      cache_size: '12 MB',
      l2_cache: '1.5 MB',
      socket_type: 'LGA 1200',
      tdp: '65W',
      integrated_graphics: 'Intel UHD Graphics 630',
      gpu_frequency: '1.20 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4',
      max_memory_speed: 'DDR4-2666',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '41.6 GB/s',
      pcie_version: 'PCIe 3.0',
    }),
    'intel-core-i5-10505-processor': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-10505',
      generation: ten,
      number_of_cores: '6 Core',
      number_of_threads: '12 Threads',
      base_clock: '3.2',
      boost_clock: '4.6',
      cache_size: '12 MB',
      l2_cache: '1.5 MB',
      socket_type: 'LGA 1200',
      tdp: '65W',
      integrated_graphics: 'Intel UHD Graphics 630',
      gpu_frequency: '1.20 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4',
      max_memory_speed: 'DDR4-2666',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '41.6 GB/s',
      pcie_version: 'PCIe 3.0',
    }),
    'intel-core-i5-10500t-processor': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-10500T',
      generation: ten,
      number_of_cores: '6 Core',
      number_of_threads: '12 Threads',
      base_clock: '2.3',
      boost_clock: '3.8',
      cache_size: '12 MB',
      l2_cache: '1.5 MB',
      socket_type: 'LGA 1200',
      tdp: '35W',
      integrated_graphics: 'Intel UHD Graphics 630',
      gpu_frequency: '1.15 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4',
      max_memory_speed: 'DDR4-2666',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '41.6 GB/s',
      pcie_version: 'PCIe 3.0',
    }),
    'intel-core-i7-10700-processor': intel({
      processor_model: 'Intel Core i7',
      model_number: 'Core i7-10700',
      generation: ten,
      number_of_cores: '8 Core',
      number_of_threads: '16 Threads',
      base_clock: '2.9',
      boost_clock: '4.8',
      cache_size: '16 MB',
      l2_cache: '2 MB',
      socket_type: 'LGA 1200',
      tdp: '65W',
      integrated_graphics: 'Intel UHD Graphics 630',
      gpu_frequency: '1.20 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4',
      max_memory_speed: 'DDR4-2933',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '46.9 GB/s',
      pcie_version: 'PCIe 3.0',
    }),
    'intel-core-i5-11400-11th-gen-processor': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-11400',
      generation: eleven,
      number_of_cores: '6 Core',
      number_of_threads: '12 Threads',
      base_clock: '2.6',
      boost_clock: '4.4',
      cache_size: '12 MB',
      l2_cache: '3 MB',
      socket_type: 'LGA 1200',
      tdp: '65W',
      max_turbo_power: '154W',
      integrated_graphics: 'Intel UHD Graphics 730',
      gpu_frequency: '1.30 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4',
      max_memory_speed: 'DDR4-3200',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '51.2 GB/s',
      pcie_version: 'PCIe 4.0',
    }),
    'intel-core-i5-11500-11th-gen-processor': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-11500',
      generation: eleven,
      number_of_cores: '6 Core',
      number_of_threads: '12 Threads',
      base_clock: '2.7',
      boost_clock: '4.6',
      cache_size: '12 MB',
      l2_cache: '3 MB',
      socket_type: 'LGA 1200',
      tdp: '65W',
      max_turbo_power: '154W',
      integrated_graphics: 'Intel UHD Graphics 750',
      gpu_frequency: '1.30 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4',
      max_memory_speed: 'DDR4-3200',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '51.2 GB/s',
      pcie_version: 'PCIe 4.0',
    }),
    'intel-core-i5-11500t-11th-gen-processor': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-11500T',
      generation: eleven,
      number_of_cores: '6 Core',
      number_of_threads: '12 Threads',
      base_clock: '1.5',
      boost_clock: '3.9',
      cache_size: '12 MB',
      l2_cache: '3 MB',
      socket_type: 'LGA 1200',
      tdp: '35W',
      integrated_graphics: 'Intel UHD Graphics 750',
      gpu_frequency: '1.20 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4',
      max_memory_speed: 'DDR4-3200',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '51.2 GB/s',
      pcie_version: 'PCIe 4.0',
    }),
    'intel-core-i3-12100-12th-gen-alder-lake-processor': intel({
      processor_model: 'Intel Core i3',
      model_number: 'Core i3-12100',
      generation: twelve,
      number_of_cores: '4 Core',
      number_of_threads: '8 Threads',
      base_clock: '3.3',
      boost_clock: '4.3',
      cache_size: '12 MB',
      l2_cache: '5 MB',
      socket_type: 'LGA 1700',
      tdp: '60W',
      max_turbo_power: '89W',
      integrated_graphics: 'Intel UHD Graphics 730',
      gpu_frequency: '1.40 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-4800',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '76.8 GB/s',
    }),
    'intel-core-i3-12100t-12th-gen-processor': intel({
      processor_model: 'Intel Core i3',
      model_number: 'Core i3-12100T',
      generation: twelve,
      number_of_cores: '4 Core',
      number_of_threads: '8 Threads',
      base_clock: '2.2',
      boost_clock: '4.1',
      cache_size: '12 MB',
      l2_cache: '5 MB',
      socket_type: 'LGA 1700',
      tdp: '35W',
      max_turbo_power: '69W',
      integrated_graphics: 'Intel UHD Graphics 730',
      gpu_frequency: '1.40 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-4800',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '76.8 GB/s',
    }),
    'intel-12th-gen-core-i5-12400-alder-lake-processor': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-12400',
      generation: twelve,
      number_of_cores: '6 Core',
      number_of_threads: '12 Threads',
      base_clock: '2.5',
      boost_clock: '4.4',
      cache_size: '18 MB',
      l2_cache: '7.5 MB',
      socket_type: 'LGA 1700',
      tdp: '65W',
      max_turbo_power: '117W',
      integrated_graphics: 'Intel UHD Graphics 730',
      gpu_frequency: '1.45 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-4800',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '76.8 GB/s',
    }),
    'intel-12th-gen-core-i5-12400f-alder-lake-processor': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-12400F',
      generation: twelve,
      number_of_cores: '6 Core',
      number_of_threads: '12 Threads',
      base_clock: '2.5',
      boost_clock: '4.4',
      cache_size: '18 MB',
      l2_cache: '7.5 MB',
      socket_type: 'LGA 1700',
      tdp: '65W',
      max_turbo_power: '117W',
      integrated_graphics: NONE,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-4800',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '76.8 GB/s',
    }),
    'intel-core-i5-12400f': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-12400F',
      generation: twelve,
      number_of_cores: '6 Core',
      number_of_threads: '12 Threads',
      base_clock: '2.5',
      boost_clock: '4.4',
      cache_size: '18 MB',
      l2_cache: '7.5 MB',
      socket_type: 'LGA 1700',
      tdp: '65W',
      max_turbo_power: '117W',
      integrated_graphics: NONE,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-4800',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '76.8 GB/s',
    }),
    'intel-12th-gen-core-i5-12500-alder-lake-processor': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-12500',
      generation: twelve,
      number_of_cores: '6 Core',
      number_of_threads: '12 Threads',
      base_clock: '3.0',
      boost_clock: '4.6',
      cache_size: '18 MB',
      l2_cache: '7.5 MB',
      socket_type: 'LGA 1700',
      tdp: '65W',
      max_turbo_power: '117W',
      integrated_graphics: 'Intel UHD Graphics 770',
      gpu_frequency: '1.45 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-4800',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '76.8 GB/s',
    }),
    'intel-12th-gen-core-i7-12700-alder-lake-processor': intel({
      processor_model: 'Intel Core i7',
      model_number: 'Core i7-12700',
      generation: twelve,
      number_of_cores: '12 Core',
      number_of_threads: '20 Threads',
      base_clock: '2.1',
      boost_clock: '4.9',
      cache_size: '25 MB',
      l2_cache: '12 MB',
      socket_type: 'LGA 1700',
      tdp: '65W',
      max_turbo_power: '180W',
      integrated_graphics: 'Intel UHD Graphics 770',
      gpu_frequency: '1.50 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-4800',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '76.8 GB/s',
    }),
    'intel-12th-gen-core-i7-12700k-alder-lake-processor': intel({
      processor_model: 'Intel Core i7',
      model_number: 'Core i7-12700K',
      generation: twelve,
      number_of_cores: '12 Core',
      number_of_threads: '20 Threads',
      base_clock: '3.6',
      boost_clock: '5.0',
      cache_size: '25 MB',
      l2_cache: '12 MB',
      socket_type: 'LGA 1700',
      tdp: '125W',
      max_turbo_power: '190W',
      integrated_graphics: 'Intel UHD Graphics 770',
      gpu_frequency: '1.50 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-4800',
      max_memory_size: '128 GB',
      max_memory_bandwidth: '76.8 GB/s',
    }),
    'intel-13th-gen-core-i5-13400-processor': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-13400',
      generation: thirteen,
      number_of_cores: '10 Core',
      number_of_threads: '16 Threads',
      base_clock: '2.5',
      boost_clock: '4.6',
      cache_size: '20 MB',
      l2_cache: '9.5 MB',
      socket_type: 'LGA 1700',
      tdp: '65W',
      max_turbo_power: '148W',
      integrated_graphics: 'Intel UHD Graphics 730',
      gpu_frequency: '1.55 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-4800',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '76.8 GB/s',
    }),
    'intel-13th-gen-core-i7-13700-processor': intel({
      processor_model: 'Intel Core i7',
      model_number: 'Core i7-13700',
      generation: thirteen,
      number_of_cores: '16 Core',
      number_of_threads: '24 Threads',
      base_clock: '2.1',
      boost_clock: '5.2',
      cache_size: '30 MB',
      l2_cache: '24 MB',
      socket_type: 'LGA 1700',
      tdp: '65W',
      max_turbo_power: '219W',
      integrated_graphics: 'Intel UHD Graphics 770',
      gpu_frequency: '1.60 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-4800',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '76.8 GB/s',
    }),
    'intel-13th-gen-core-i7-13700k-processor': intel({
      processor_model: 'Intel Core i7',
      model_number: 'Core i7-13700K',
      generation: thirteen,
      number_of_cores: '16 Core',
      number_of_threads: '24 Threads',
      base_clock: '3.4',
      boost_clock: '5.4',
      cache_size: '30 MB',
      l2_cache: '24 MB',
      socket_type: 'LGA 1700',
      tdp: '125W',
      max_turbo_power: '253W',
      integrated_graphics: 'Intel UHD Graphics 770',
      gpu_frequency: '1.60 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-5600',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '89.6 GB/s',
    }),
    'intel-13th-gen-core-i7-13700kf-processor': intel({
      processor_model: 'Intel Core i7',
      model_number: 'Core i7-13700KF',
      generation: thirteen,
      number_of_cores: '16 Core',
      number_of_threads: '24 Threads',
      base_clock: '3.4',
      boost_clock: '5.4',
      cache_size: '30 MB',
      l2_cache: '24 MB',
      socket_type: 'LGA 1700',
      tdp: '125W',
      max_turbo_power: '253W',
      integrated_graphics: NONE,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-5600',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '89.6 GB/s',
    }),
    'intel-core-i3-14100': intel({
      processor_model: 'Intel Core i3',
      model_number: 'Core i3-14100',
      generation: fourteen,
      number_of_cores: '4 Core',
      number_of_threads: '8 Threads',
      base_clock: '3.5',
      boost_clock: '4.7',
      cache_size: '12 MB',
      l2_cache: '5 MB',
      socket_type: 'LGA 1700',
      tdp: '60W',
      max_turbo_power: '110W',
      integrated_graphics: 'Intel UHD Graphics 730',
      gpu_frequency: '1.5 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-4800',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '76.8 GB/s',
    }),
    'intel-core-i3-14100-14th-gen-processor': intel({
      processor_model: 'Intel Core i3',
      model_number: 'Core i3-14100',
      generation: fourteen,
      number_of_cores: '4 Core',
      number_of_threads: '8 Threads',
      base_clock: '3.5',
      boost_clock: '4.7',
      cache_size: '12 MB',
      l2_cache: '5 MB',
      socket_type: 'LGA 1700',
      tdp: '60W',
      max_turbo_power: '110W',
      integrated_graphics: 'Intel UHD Graphics 730',
      gpu_frequency: '1.5 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-4800',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '76.8 GB/s',
    }),
    'intel-core-i5-14400-14th-gen-processor': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-14400',
      generation: fourteen,
      number_of_cores: '10 Core',
      number_of_threads: '16 Threads',
      base_clock: '2.5',
      boost_clock: '4.7',
      cache_size: '20 MB',
      l2_cache: '9.5 MB',
      socket_type: 'LGA 1700',
      tdp: '65W',
      max_turbo_power: '148W',
      integrated_graphics: 'Intel UHD Graphics 730',
      gpu_frequency: '1.55 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-4800',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '76.8 GB/s',
    }),
    'intel-core-i5-14400f-14th-gen-raptor-lake-processor': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-14400F',
      generation: fourteen,
      number_of_cores: '10 Core',
      number_of_threads: '16 Threads',
      base_clock: '2.5',
      boost_clock: '4.7',
      cache_size: '20 MB',
      l2_cache: '9.5 MB',
      socket_type: 'LGA 1700',
      tdp: '65W',
      max_turbo_power: '148W',
      integrated_graphics: NONE,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-4800',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '76.8 GB/s',
    }),
    'intel-core-i5-14500-14th-gen-processor': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-14500',
      generation: fourteen,
      number_of_cores: '14 Core',
      number_of_threads: '20 Threads',
      base_clock: '2.6',
      boost_clock: '5.0',
      cache_size: '24 MB',
      l2_cache: '11.5 MB',
      socket_type: 'LGA 1700',
      tdp: '65W',
      max_turbo_power: '154W',
      integrated_graphics: 'Intel UHD Graphics 770',
      gpu_frequency: '1.55 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-4800',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '76.8 GB/s',
    }),
    'intel-core-i5-14600k': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-14600K',
      generation: fourteen,
      number_of_cores: '14 Core',
      number_of_threads: '20 Threads',
      base_clock: '3.5',
      boost_clock: '5.3',
      cache_size: '24 MB',
      l2_cache: '20 MB',
      socket_type: 'LGA 1700',
      tdp: '125W',
      max_turbo_power: '181W',
      integrated_graphics: 'Intel UHD Graphics 770',
      gpu_frequency: '1.55 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-5600',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '89.6 GB/s',
    }),
    'intel-14th-gen-core-i5-14600k-processor': intel({
      processor_model: 'Intel Core i5',
      model_number: 'Core i5-14600K',
      generation: fourteen,
      number_of_cores: '14 Core',
      number_of_threads: '20 Threads',
      base_clock: '3.5',
      boost_clock: '5.3',
      cache_size: '24 MB',
      l2_cache: '20 MB',
      socket_type: 'LGA 1700',
      tdp: '125W',
      max_turbo_power: '181W',
      integrated_graphics: 'Intel UHD Graphics 770',
      gpu_frequency: '1.55 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-5600',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '89.6 GB/s',
    }),
    'intel-core-i7-14700-14th-gen-processor': intel({
      processor_model: 'Intel Core i7',
      model_number: 'Core i7-14700',
      generation: fourteen,
      number_of_cores: '20 Core',
      number_of_threads: '28 Threads',
      base_clock: '2.1',
      boost_clock: '5.4',
      cache_size: '33 MB',
      l2_cache: '28 MB',
      socket_type: 'LGA 1700',
      tdp: '65W',
      max_turbo_power: '219W',
      integrated_graphics: 'Intel UHD Graphics 770',
      gpu_frequency: '1.60 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-5600',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '89.6 GB/s',
    }),
    'intel-core-i7-14700k': intel({
      processor_model: 'Intel Core i7',
      model_number: 'Core i7-14700K',
      generation: fourteen,
      number_of_cores: '20 Core',
      number_of_threads: '28 Threads',
      base_clock: '3.4',
      boost_clock: '5.6',
      cache_size: '33 MB',
      l2_cache: '28 MB',
      socket_type: 'LGA 1700',
      tdp: '125W',
      max_turbo_power: '253W',
      integrated_graphics: 'Intel UHD Graphics 770',
      gpu_frequency: '1.60 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-5600',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '89.6 GB/s',
    }),
    'intel-14th-gen-core-i7-14700k-processor': intel({
      processor_model: 'Intel Core i7',
      model_number: 'Core i7-14700K',
      generation: fourteen,
      number_of_cores: '20 Core',
      number_of_threads: '28 Threads',
      base_clock: '3.4',
      boost_clock: '5.6',
      cache_size: '33 MB',
      l2_cache: '28 MB',
      socket_type: 'LGA 1700',
      tdp: '125W',
      max_turbo_power: '253W',
      integrated_graphics: 'Intel UHD Graphics 770',
      gpu_frequency: '1.60 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-5600',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '89.6 GB/s',
    }),
    'intel-14th-gen-core-i7-14700kf-processor': intel({
      processor_model: 'Intel Core i7',
      model_number: 'Core i7-14700KF',
      generation: fourteen,
      number_of_cores: '20 Core',
      number_of_threads: '28 Threads',
      base_clock: '3.4',
      boost_clock: '5.6',
      cache_size: '33 MB',
      l2_cache: '28 MB',
      socket_type: 'LGA 1700',
      tdp: '125W',
      max_turbo_power: '253W',
      integrated_graphics: NONE,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-5600',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '89.6 GB/s',
    }),
    'intel-14th-gen-core-i9-14900k-processor': intel({
      processor_model: 'Intel Core i9',
      model_number: 'Core i9-14900K',
      generation: fourteen,
      number_of_cores: '24 Core',
      number_of_threads: '32 Threads',
      base_clock: '3.2',
      boost_clock: '6.0',
      cache_size: '36 MB',
      l2_cache: '32 MB',
      socket_type: 'LGA 1700',
      tdp: '125W',
      max_turbo_power: '253W',
      integrated_graphics: 'Intel UHD Graphics 770',
      gpu_frequency: '1.65 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-5600',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '89.6 GB/s',
    }),
    'intel-14th-gen-core-i9-14900kf-processor': intel({
      processor_model: 'Intel Core i9',
      model_number: 'Core i9-14900KF',
      generation: fourteen,
      number_of_cores: '24 Core',
      number_of_threads: '32 Threads',
      base_clock: '3.2',
      boost_clock: '6.0',
      cache_size: '36 MB',
      l2_cache: '32 MB',
      socket_type: 'LGA 1700',
      tdp: '125W',
      max_turbo_power: '253W',
      integrated_graphics: NONE,
      memory_type: 'DDR4 + DDR5',
      max_memory_speed: 'DDR5-5600',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '89.6 GB/s',
    }),
    'intel-core-ultra-5-225-processor': intel({
      processor_model: 'Intel Core Ultra 5',
      model_number: 'Core Ultra 5 225',
      generation: ultra2,
      number_of_cores: '10 Core',
      number_of_threads: '10 Threads',
      base_clock: '3.3',
      boost_clock: '4.9',
      cache_size: '20 MB',
      l2_cache: '22 MB',
      socket_type: 'LGA 1851',
      tdp: '65W',
      max_turbo_power: '121W',
      integrated_graphics: 'Intel Arc Graphics',
      gpu_frequency: '1.8 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR5',
      max_memory_speed: 'DDR5-6400',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '102.4 GB/s',
    }),
    'intel-core-ultra-5-245k-processor': intel({
      processor_model: 'Intel Core Ultra 5',
      model_number: 'Core Ultra 5 245K',
      generation: ultra2,
      number_of_cores: '14 Core',
      number_of_threads: '14 Threads',
      base_clock: '4.2',
      boost_clock: '5.2',
      cache_size: '24 MB',
      l2_cache: '26 MB',
      socket_type: 'LGA 1851',
      tdp: '125W',
      max_turbo_power: '159W',
      integrated_graphics: 'Intel Arc Graphics',
      gpu_frequency: '1.9 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR5',
      max_memory_speed: 'DDR5-6400',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '102.4 GB/s',
    }),
    'intel-core-ultra-5-250k-plus-processor': intel({
      processor_model: 'Intel Core Ultra 5',
      model_number: 'Core Ultra 5 250K Plus',
      generation: ultra2,
      number_of_cores: '18 Core',
      number_of_threads: '18 Threads',
      base_clock: '4.2',
      boost_clock: '5.3',
      cache_size: '30 MB',
      l2_cache: '30 MB',
      socket_type: 'LGA 1851',
      tdp: '125W',
      max_turbo_power: '159W',
      integrated_graphics: 'Intel Arc Graphics',
      gpu_frequency: '1.9 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR5',
      max_memory_speed: 'DDR5-7200',
      max_memory_size: '256 GB',
      max_memory_bandwidth: '115.2 GB/s',
    }),
    'intel-core-ultra-7-265k': intel({
      processor_model: 'Intel Core Ultra 7',
      model_number: 'Core Ultra 7 265K',
      generation: ultra2,
      number_of_cores: '20 Core',
      number_of_threads: '20 Threads',
      base_clock: '3.9',
      boost_clock: '5.5',
      cache_size: '30 MB',
      l2_cache: '36 MB',
      socket_type: 'LGA 1851',
      tdp: '125W',
      max_turbo_power: '250W',
      integrated_graphics: 'Intel Arc Graphics',
      gpu_frequency: '2.0 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR5',
      max_memory_speed: 'DDR5-6400',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '102.4 GB/s',
    }),
    'intel-core-ultra-7-270k-plus-processor': intel({
      processor_model: 'Intel Core Ultra 7',
      model_number: 'Core Ultra 7 270K Plus',
      generation: ultra2,
      number_of_cores: '24 Core',
      number_of_threads: '24 Threads',
      base_clock: '3.7',
      boost_clock: '5.5',
      cache_size: '36 MB',
      l2_cache: '40 MB',
      socket_type: 'LGA 1851',
      tdp: '125W',
      max_turbo_power: '250W',
      integrated_graphics: 'Intel Arc Graphics',
      gpu_frequency: '2.0 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR5',
      max_memory_speed: 'DDR5-7200',
      max_memory_size: '256 GB',
      max_memory_bandwidth: '115.2 GB/s',
    }),
    'intel-core-ultra-9-285k-processor': intel({
      processor_model: 'Intel Core Ultra 9',
      model_number: 'Core Ultra 9 285K',
      generation: ultra2,
      number_of_cores: '24 Core',
      number_of_threads: '24 Threads',
      base_clock: '3.7',
      boost_clock: '5.7',
      cache_size: '36 MB',
      l2_cache: '40 MB',
      socket_type: 'LGA 1851',
      tdp: '125W',
      max_turbo_power: '250W',
      integrated_graphics: 'Intel Arc Graphics',
      gpu_frequency: '2.0 GHz',
      max_resolution: INTEL_UHD_RES,
      memory_type: 'DDR5',
      max_memory_speed: 'DDR5-6400',
      max_memory_size: '192 GB',
      max_memory_bandwidth: '102.4 GB/s',
    }),
  };

  return rows;
}

Object.assign(PROCESSOR_OFFICIAL_SPECS, addIntelBatch());
